### ISSUE TITLE
Cannot read property from mongoDB

### ISSUE THREAD

**Issue by Abdizriel** [ForbesLindesay/connect-roles#38]
I've got User schema with role parameter. I'm using your example with usage of connect-roles (I changed var user to var role and configured permissions:

    role.use('profile.view', function (req) {
        if(req.user.role === 'user') {
           return true;
        }
    });
    role.use(function (req) {
        if (req.user.role === 'admin') {
            return true;
        }
    });

Those are my configured routes:

    app.get('/profile', role.can('profile.view'), function(req, res) {
      profile.profile(req, res);
    });
    app.get('/admin', role.is('admin.'), function(req, res){
        admin.admin(req, res);
    });

In view I'm using

    if userIs('admin')
        li
	    a(href='/admin')
	        |  Admin
	li
	    a(href='/profile')
	        |  Profile
	li
	    a(href='/logout')
	        |  Log Out

However I've issue when I've:

    role.use(function (req) {
        if (req.user.role === 'admin') {
            return true;
        }
    });

That: Cannot read property 'role' of undefined

When I'm deleting this rule it's working correct however I don't have admin menu.

**Comment by ForbesLindesay** [comment]
Sorry for the slow response.  It looks like you are probably only getting this with un-authenticated users.  Hence `req.user` being undefined.  What you may want to do is add another rule (before all the other rules) that looks like:

```js
role.use(function (req) {
    if (!req.user) {
        return false;
    }
});
```

i.e. if there is no user, don't let them do anything.
