### ISSUE TITLE
Is Express 3 still supported ?

### ISSUE THREAD

**Issue by joe-mojo** [ForbesLindesay/connect-roles#40]
I have an issue with connect-roles 3.1.1 where :
- I'm using Express 3.x (legacy app)
- passport is OK (blocking if not connected)
- connect-role strategies are ok : returning true if the connected user has the right role ; user with the wrong role fire the failureHandler as expected

**but** :
-  when strategy returns true, the result is 404 and my route is never called.

**Comment by ForbesLindesay** [comment]
I can't help you without examples of the code you're attempting to use.
