### ISSUE TITLE
express deprecated res.send(status) Use res.sendStatus(status) instead

### ISSUE THREAD

**Issue by kapouer** [ForbesLindesay/connect-roles#41]
Hello,

```
(res.sendStatus || res.send).bind(res)(status);
```

keeps backward compatibility and silences express 4.1x.

**Comment by pablovilas** [comment]
I've just made a pr with your sugestion: https://github.com/ForbesLindesay/connect-roles/pull/47

**Comment by dskrvk** [comment]
PR was merged. This can be closed now.
