### ISSUE TITLE
how do you use connect-roles with fullstack meanjs

### ISSUE THREAD

**Issue by dladiguna** [ForbesLindesay/connect-roles#42]
I'm learning meanjs and i learned that one of the best authorization to be combined with passportjs authentication is connect-roles. I can't found any documentation on how to use connect-roles and passportjs together on the fullstack meanjs. Can you please provide one? Thank you

**Comment by ForbesLindesay** [comment]
See the "usage" example but replace `app.use(authentication)` and `var authentication = require('your-authentication-module-here');` with the code for setting up passportjs
