### ISSUE TITLE
Chaining User.is() checks doesn't work

### ISSUE THREAD

**Issue by Rambou** [ForbesLindesay/connect-roles#48]
I'm trying to do something like app.post('/api/user/', User.is(Role.accountOwner), User.is(Role.secretariat), function(req,res,next){ do some stuff here} );

but doesn't work properly. When user's role is **accountOwner** everything works fine, if user is **secreteriat** throws forbidden because user is not **accountOwner** and the function that check if user is accountOwner throws null. In the documentation your said that the above line of code would work. Checking multiple user roles should work fine, but it doesn't. Could you provide more info or example on the issue?

**Comment by ForbesLindesay** [comment]
connect roles doesn't support an "or" operation at this time.  Your code is checking that the user is "accountOwner" **and** "secretariat".  The recommended approach is instead to do `User.can('post to user')` and then define a capability called "post to user" which allows either account owners or secretariats
