### ISSUE TITLE
Mongodb built-in roles

### ISSUE THREAD

**Issue by Globik** [ForbesLindesay/connect-roles#50]
Any chance to integrate with mongo's built-in roles and privelliges?

**Comment by ForbesLindesay** [comment]
What would that look like?

**Comment by Globik** [comment]
var user = db.systems.users.find user By Id()
If user.role == mainAdmin then ok for edite and update...
Please tell me, is an authorization as it is is undependent on any db?

**Comment by markstos** [comment]
This seems like something that would be provided separately, not part of this distribution.

**Comment by Globik** [comment]
One may close this issue.
